name: release

on:
  workflow_dispatch:
    inputs:
      kustomize_version:
        description: 'Tag to release kustomize'
        required: true
      libs_version:
        description: 'Tag to release libs'
        required: true

permissions:
  contents: write # Allow actions to push changes

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v5
    - name: Create a branch for the release
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git config --global push.default current

        go tool gorepomod pre-release --local --doIt "${{ github.event.inputs.kustomize_version }}"

    - name: Set up Go 1.x
      uses: actions/setup-go@v6
      with:
        go-version-file: go.work
      id: go

    - name: Release kyaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make IS_LOCAL=true verify-kustomize-repo
        go tool gorepomod release --local kyaml ${{ github.event.inputs.libs_version }} --doIt
        ./releasing/create-release.sh kyaml/${{ github.event.inputs.libs_version }}
        go tool gorepomod pin kyaml --doIt
        git commit -m "Update kyaml to ${{ github.event.inputs.libs_version }}"
        git push --force

    - name: Release cmd/config
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make IS_LOCAL=true verify-kustomize-repo
        go tool gorepomod release --local cmd/config ${{ github.event.inputs.libs_version }} --doIt
        ./releasing/create-release.sh cmd/config/${{ github.event.inputs.libs_version }}
        go tool gorepomod pin cmd/config --doIt
        git commit -m "Update cmd/config to ${{ github.event.inputs.libs_version }}"
        git push --force

    - name: Release api
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make IS_LOCAL=true verify-kustomize-repo
        go tool gorepomod release --local api ${{ github.event.inputs.libs_version }} --doIt
        ./releasing/create-release.sh api/${{ github.event.inputs.libs_version }}
        go tool gorepomod pin api --doIt
        git commit -m "Update api to ${{ github.event.inputs.libs_version }}"
        git push --force

    - name: Release kustomize
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make IS_LOCAL=true verify-kustomize-repo
        go tool gorepomod release --local kustomize ${{ github.event.inputs.kustomize_version }} --doIt
        ./releasing/create-release.sh kustomize/${{ github.event.inputs.kustomize_version }}

    - name: Push changes
      run: |
        git switch master
        git pull origin master
        sed -i "" "s/LATEST_RELEASE=.*/LATEST_RELEASE=${{ github.event.inputs.kustomize_version }}/" Makefile
        source ./releasing/helpers.sh
        createBranch bumpMakefile "Update LATEST_RELEASE to ${{ github.event.inputs.kustomize_version }}"
